### ISSUE TITLE
Allow removing the need for Cordova file and file transfer plugins 

### ISSUE THREAD

**Issue by HarelM** [qrclip/capacitor-file-chunk#1]
## Motivation
File transfer plugin didn't have a release in a few year and the latest code has some fixes that are needed.
File plugin released version is broken and I'm using a branch.
Bottom line, Cordova maintenance is lacking at best and I can't continue to relay on their plugins.
The files that I download and use are for offline to show maps, these files are around 500Mb in total and around 100-200Mb each.
In order to stop the need to relay on Cordova pluings there are a few things that I need to be able to do:
1. Download large files - when downloading a large file using fetch it saves the entire file to memory and then pass it through the cordova interface to the file system, this is not great and downloading using native code straight to the file system is a lot faster and uses a lot less resources.
2. Open large files that are saved in the file system.
3. Get file name and extension

The following is more or less where I use these plugins in my code:
https://github.com/IsraelHikingMap/Site/blob/f43fd3b1f05b7f6bef45ee182486fcf08d5249cf/IsraelHiking.Web/src/application/services/file.service.ts
Search for the following:
`this.fileSystemWrapper` - When I read from the cache folder for example the file is large as I download to the cache a large file.
`this.fileTransfer` - Used to download large files

I think I managed to move all other logic to use the capacitor file, but here is where I couldn't.
I'll be happy to test stuff and help push this forward. I fear the day the Cordova plugins will stop functioning...

**Comment by qrclip** [comment]
Thank you for your information on your use case. I will work on adding a download sample to the demo app that you can use to test and evaluate the performance for your specific scenario.

Regarding the storage of the map files, could you please let me know where they are hosted? Are they stored on Amazon S3, your own servers or some other platform? Handling 200 MB files should not be a problem, especially when reading from the system cache folder. Also, if the file format allows, you can further streamline the process by reading only certain parts of the file. For example, if the file starts with an index, you can directly access the information you need, resulting in a significant speed increase.

**Comment by HarelM** [comment]
One of the files is hosted here: and I need to save it to the cache folder before opening it and populating the indexdb with its content:
http://israelhiking.osm.org.il/PointsOfInterest/pois.zip
Other files can be downloaded from open map tiles I think, See here:
https://data.maptiler.com/downloads/tileset/osm/asia/israel-and-palestine/

Let me know if you need any more info.

**Comment by HarelM** [comment]
Also note, that when downloading some files there's a need to authenticate using the Authorization header, so this needs to be supported as well I guess...

**Comment by qrclip** [comment]
I've made some updates to the demo app to allow for more examples to be added in the future. The first example demonstrates the use of fetch with range headers, which you can find here:
https://github.com/qrclip/capacitor-file-chunk/blob/main/demo/src/app/download01/download01.page.ts

I've set up a small test file on my CDN: https://cdn.qrclip.io/dev/pi.zip. It's not a zip file, but due to CORS, it was easier to rename it. It's actually a text file containing repeated digits of pi, totaling around 26MB in size. This example downloads the file to cache and reads a chunk of it. It works with large files, as long as the server supports range headers. I plan to add more examples in the future, but keep in mind that they will load the entire file into memory using XMLHttpRequest, although writing the file should be straightforward.

This current example is efficient in terms of memory usage because it writes each chunk as soon as it's ready before downloading another. There's a class called DownloadFetchRange in the demo app that you can use for testing in your project. Note that encryption is turned off within the class, but this may not be a concern for your use case.

**Comment by HarelM** [comment]
Thanks for the info. I'll see if I can find the time to see if my server supports range requests and that I can use this plugin and the code you wrote.
Does the plugin code has the download fetch range class in it or do I need to copy it to my project?

**Comment by qrclip** [comment]
Yes, just use this class:
https://github.com/qrclip/capacitor-file-chunk/blob/main/demo/src/app/download01/download-fetch-range.ts

It has two observables, one for progress and one for error. And the downloadFile(tUrl: string, tPath: string, tDirectory: Directory). I use bunny cdn for my cdn, amazon s3 should work too. When I've more examples I'll create a separate library, because I don't want to add to the plugin.

**Comment by HarelM** [comment]
I've started looking into this seriously, but it seems too complicated.
The instruction in the readme on how to add this plugin are somewhat complicated.
Yes, they are written fine, but I would prefer them to be done automatically when I `npm install` the plugin, also there's a dependency on capacitor file system that is not mentioned.
It looks like I need to manage a server for this, is this only for previous versions or also for this version as well?
There are utilities that are used to make things easier, I shouldn't be coping them to my project, but instead they should be available in the npm package - the range download and the manager.
It's a lot of code to include to be able to simply - read a file using chunks or write one.
What I basically would like to do is update the following file in my project:
https://github.com/IsraelHikingMap/Site/blob/d43a0655b5bc8dc0e6902188acfa29f3b7f928cf/IsraelHiking.Web/src/application/services/file.service.ts
This file doesn't have a lot of references to file and file transfer plugin, but I still need to change every call there.
I don't want to bother about chunks, their size and their offset, I want it to work.
Yes, the low level API is important to have for edge cases, but I think there's a need to have a high level API as part of the plugin.
Thanks for all the hard work around this!

**Comment by qrclip** [comment]
Yes, I understand. The only problem is that I need to do some things in the app itself to fix this big problem with Capactitor. Since I can't read the entire file into memory, it would just crash. So the app has to deal with something that there are many options for and is very backend dependent. Right now I don't have time, but it would be easy to develop something plug-and-play that works with S3. Also the localhost is just for speed, but brings a lot of ballast (encryption libraries). It's possible to use just the capacitor bridge (slower), but for smaller files under 1GB it should do. Once I've some time, I'll try to develop a plug-and-play solution that works with a simple npm installation.
Thanks a lot for your time,
