### ISSUE TITLE
FileChunk won't start in a web worker in an Ionic project

### ISSUE THREAD

**Issue by jkyoutsey** [qrclip/capacitor-file-chunk#10]
On a physical device I'm getting the FIleChunk failed to start error when I try to execute the download in a web worker. If it's not in a web worker it works fine. Is there something in the FileChunk that attempts to access the DOM in some way?

It would be good if this would work in a web worker so we could avoid blocking the main thread in a JS context.

**Comment by qrclip** [comment]
Hello,
Are you using the web server or the readFileChunk function? I've never tested the readFileChunk version in Webworker, but the web server version works as you can make a fetch request to it and that's how it was implemented in the QRClip app. I'll see what I can do, because the web server version is out of the question for iOS because the app stops completely when it goes into the background. I can't promise I can do it right away, but I'll see what I can do.

this works inside the webworker:
` 
const tResp = await fetch(tFile.fileChunk.path + '?o=' + tStart.toString() + '&l=' + tSize.toString(), {
headers: { authorization: tFile.fileChunk.authToken },
method: 'get',
});
`

**Comment by jkyoutsey** [comment]
Actually, I'm using DownloadFetchRange class, and it appears to start the server. I guess I should NOT be using that since that's not going to work for iOS? Can you point me to an example of how to use readFileChunk instead? I backed off of the webworker because of this issue and am using it directly, so if readFileChunk works then I should probably switch to using that.

**Comment by qrclip** [comment]
Hello,

The problem with iOS and the web server is that as soon as it goes to the background, it stops immediately, but when the app is in the foreground, it works. Using the capacitor bridge is slower especially on Android, but it works. The only problem is that it doesn't work on the web server, I'll have to try to get it working there.

For your problem you need to replace the call to this function in the demo:
appendChunkToFile to the Capacitor file system and append it to the file. If you only write, you don't need the plugin. With the capacitor file system you can append to a file. The only thing you need this plugin for is to read chunks when you are not using the web server for speed.

Thank you
